### ISSUE TITLE
Add latitude and longitude

### ISSUE THREAD

**Issue by tapaswenipathak** [nshntarora/Indian-Cities-JSON#1]
How about lat and log for the cities?

**Comment by nshntarora** [comment]
Just added a detailed version to the repo, this one has more cities, and latitude and longitude for each.
https://github.com/nshntarora/Indian-Cities-JSON/blob/master/a-detailed-version.json

**Comment by DollarAkshay** [comment]
@nshntarora Contains a lot of duplicate information
