### ISSUE TITLE
Duplicate Cities

### ISSUE THREAD

**Issue by rahulakrishna** [nshntarora/Indian-Cities-JSON#13]
Many cities exist twice. Causing a pretty serious problem in React because I'm using the city name as the key.

**Comment by nshntarora** [comment]
Hey @rahulakrishna 
Two states might have a city with the same name. There's a city called Rudrapur near Nainital and another one near Gorakhpur. So, I'd suggest use the iteration ID, or the combination of city and state as a key.

If there are some city names that are repeated with the same state, let me know :smile:
